# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: zh

pipeline:
  # # No configuration for the NLU pipeline was provided. The following default pipeline was used to train your model.
  # # If you'd like to customize it, uncomment and adjust the pipeline.
  # # See https://rasa.com/docs/rasa/tuning-your-model for more information.
  #  - name: compoments.nlu.helpers.correction.TextCorrection # 文本纠错 Component
  - name: compoments.nlu.tokenizers.bert_tokenizer.CustomBertTokenizer # bert分词器
    cache_dir: ./tmp
    model_weights: pre_models
  - name: compoments.nlu.featurizer.lm_featurizer.OnnxLanguageModelFeaturizer # bert特征器
    cache_dir: ./tmp
    model_name: bert
    model_weights: pre_models
    onnx: false  # 因为有依赖，默认未开启
    quantize: false
  - name: RegexFeaturizer
    # Text will be processed with case sensitive as default
    case_sensitive: False
    # use match word boundaries for lookup table
    use_word_boundaries: False
  - name: DIETClassifier # Dual Intent Entity Transformer (DIET) 用于意图分类和实体提取
    epochs: 100
  - name: RegexEntityExtractor # 使用训练数据中定义的查找表（lookup table）和/或正则表达式提取实体
    use_word_boundaries: False #中文环境要用
    use_lookup_tables: True
    use_regexes: True
  - name: EntitySynonymMapper # 将同义实体值映射到相同的值。
  - name: ResponseSelector
    epochs: 100
    retrieval_intent: 选课问题 # 只针对faq检索意图训练响应选择器模型
  - name: ResponseSelector
    epochs: 100
    retrieval_intent: 火车票优惠 # 只针对faq检索意图训练响应选择器模型
  - name: ResponseSelector
    epochs: 100
    retrieval_intent: 心理咨询 # 只针对faq检索意图训练响应选择器模型
  - name: ResponseSelector
    epochs: 100
    retrieval_intent: 图书馆服务 # 只针对faq检索意图训练响应选择器模型
  - name: ResponseSelector
    epochs: 100
    retrieval_intent: 就业指导 # 只针对faq检索意图训练响应选择器模型
  - name: ResponseSelector
    epochs: 100
    retrieval_intent: 校园卡 # 只针对faq检索意图训练响应选择器模型
  - name: ResponseSelector
    retrieval_intent: out_of_scope # 超出范围的意图
    scale_loss: false
    epochs: 100
  - name: ResponseSelector
    retrieval_intent: chitchat # 闲聊
    scale_loss: false
    epochs: 100
  - name: FallbackClassifier # 如果NLU意图分类不明确，则使用意图nlu_fallback对消息进行分类。置信度设置为与回退阈值相同。
    threshold: 0.7
    ambiguity_threshold: 0.1

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  # # No configuration for policies was provided. The following default policies were used to train your model.
  # # If you'd like to customize them, uncomment and adjust the policies.
  # # See https://rasa.com/docs/rasa/policies for more information.
  - name: AugmentedMemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
#  - name: compoments.polices.ask_again_policy.AskAgainRulePolicy # 支持再问一次，比如问了“深圳天气”之后再问“那成都呢”。
#    core_fallback_threshold: 0.5
#    ask_again_intent: "再问一次"
#    need_ask_again_intents:
#      - "查询天气"
  - name: RulePolicy
    core_fallback_threshold: 0.3
    core_fallback_action_name: "action_default_fallback"
    enable_fallback_prediction: True

