# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: zh

pipeline:
  # # No configuration for the NLU pipeline was provided. The following default pipeline was used to train your model.
  # # If you'd like to customize it, uncomment and adjust the pipeline.
  # # See https://rasa.com/docs/rasa/tuning-your-model for more information.
  #  - name: compoments.nlu.helpers.correction.TextCorrection # 文本纠错 Component
  - name: compoments.nlu.tokenizers.bert_tokenizer.CustomBertTokenizer # bert分词器
    cache_dir: ./tmp
    model_weights: pre_models
  - name: compoments.nlu.featurizer.lm_featurizer.OnnxLanguageModelFeaturizer # bert特征器
    cache_dir: ./tmp
    model_name: bert
    model_weights: pre_models
    onnx: false  # 因为有依赖，默认未开启
    quantize: false
  - name: RegexFeaturizer
    # During training the RegexFeaturizer creates a list of regular expressions defined in the training data format.
    # For each regex, a feature will be set marking whether this expression was found in the user message or not.
    # All features will later be fed into an intent classifier / entity extractor to simplify classification
    # 设置大小写不敏感
    case_sensitive: False
    # 中文不使用空格进行分词的语言，需要设置 use_word_boundaries: False
    use_word_boundaries: False
  - name: DIETClassifier # Dual Intent Entity Transformer (DIET) 用于意图分类和实体提取
    epochs: 100
  - name: RegexEntityExtractor # 使用训练数据中定义的查找表（lookup table）和/或正则表达式提取实体
    use_word_boundaries: False # 中文环境设置为False
    use_lookup_tables: True
    use_regexes: True
  - name: EntitySynonymMapper # 将同义实体值映射到相同的值。
  - name: ResponseSelector
    epochs: 100
    retrieval_intent: 教学教务 # 只针对faq检索意图训练响应选择器模型
  - name: ResponseSelector
    epochs: 100
    retrieval_intent: 奖助学金 # 只针对faq检索意图训练响应选择器模型
  - name: ResponseSelector
    epochs: 100
    retrieval_intent: 补考缓考 # 只针对faq检索意图训练响应选择器模型
  - name: ResponseSelector
    epochs: 100
    retrieval_intent: 选课事宜 # 只针对faq检索意图训练响应选择器模型
  - name: ResponseSelector
    epochs: 100
    retrieval_intent: 专业修读 # 只针对faq检索意图训练响应选择器模型
  - name: ResponseSelector
    epochs: 100
    retrieval_intent: 后勤服务 # 只针对faq检索意图训练响应选择器模型
  - name: ResponseSelector
    epochs: 100
    retrieval_intent: 宿舍服务 # 只针对faq检索意图训练响应选择器模型
  - name: ResponseSelector
    epochs: 100
    retrieval_intent: 图书馆服务 # 只针对faq检索意图训练响应选择器模型
  - name: ResponseSelector
    epochs: 100
    retrieval_intent: 就业指导 # 只针对faq检索意图训练响应选择器模型
  - name: ResponseSelector
    epochs: 100
    retrieval_intent: 学生证件 # 只针对faq检索意图训练响应选择器模型
  - name: ResponseSelector
    epochs: 100
    retrieval_intent: 校医院 # 只针对faq检索意图训练响应选择器模型
  - name: ResponseSelector
    epochs: 100
    retrieval_intent: 校园网服务 # 只针对faq检索意图训练响应选择器模型
  - name: ResponseSelector
    epochs: 100
    retrieval_intent: 本科生招生 # 只针对faq检索意图训练响应选择器模型
  - name: ResponseSelector
    epochs: 100
    retrieval_intent: 研究生招生 # 只针对faq检索意图训练响应选择器模型
  - name: ResponseSelector
    epochs: 100
    retrieval_intent: 迎新服务 # 只针对faq检索意图训练响应选择器模型
  - name: ResponseSelector
    epochs: 100
    retrieval_intent: 常用联系方式 # 只针对faq检索意图训练响应选择器模型
  - name: ResponseSelector
    retrieval_intent: out_of_scope # 超出范围的意图
    scale_loss: false
    epochs: 100
  - name: ResponseSelector
    retrieval_intent: chitchat # 闲聊
    scale_loss: false
    epochs: 100
  - name: FallbackClassifier # 如果NLU意图分类不明确，则使用意图nlu_fallback对消息进行分类。置信度设置为与回退阈值相同。
    threshold: 0.9
    ambiguity_threshold: 0.1

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  # # No configuration for policies was provided. The following default policies were used to train your model.
  # # If you'd like to customize them, uncomment and adjust the policies.
  # # See https://rasa.com/docs/rasa/policies for more information.
  - name: AugmentedMemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
  #  - name: compoments.polices.ask_again_policy.AskAgainRulePolicy # 支持再问一次，比如问了“深圳天气”之后再问“那成都呢”。
  #    core_fallback_threshold: 0.5
  #    ask_again_intent: "再问一次"
  #    need_ask_again_intents:
  #      - "查询天气"
  - name: RulePolicy
    core_fallback_threshold: 0.3
    core_fallback_action_name: "action_default_fallback"
    enable_fallback_prediction: True

